### ISSUE TITLE
Sort version numbers as version numbers.

### ISSUE THREAD

**Issue by domdfcoding** [pypi/inspector#11] opened 2022-06-06 18:50 UTC
Currently the version numbers are sorted as strings (e.g. 0.1, 0.10, 0.11, 0.2) rather than as version numbers (e.g. 0.1, 0.2, 0.10)

See for instance https://inspector.pypi.io/project/whey/

**Comment by di** [comment] 2022-06-06 18:54
Duplicate of https://github.com/pypi/inspector/issues/3.

**Closed by di** 2022-06-06 18:54 UTC
